# golangci-lint configuration for arrest-go main package
run:
  timeout: 5m
  go: '1.21'
  modules-download-mode: readonly

output:
  format: colored-line-number
  print-issued-lines: true
  print-linter-name: true

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true

  govet:
    enable-all: true
    disable:
      - fieldalignment # Can be too noisy for this project

  gocyclo:
    min-complexity: 15

  gofmt:
    simplify: true

  goimports:
    local-prefixes: github.com/zostay/arrest-go

  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
    disabled-checks:
      - whyNoLint # We use nolint comments appropriately

  funlen:
    lines: 100
    statements: 50

  lll:
    line-length: 120

  misspell:
    locale: US

  prealloc:
    simple: true
    range-loops: true
    for-loops: false

  unparam:
    check-exported: false

  unused:
    check-exported: false

  whitespace:
    multi-if: false
    multi-func: false

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - typecheck
    - unused
    - varcheck
    - deadcode
    - structcheck
    - gocyclo
    - gofmt
    - goimports
    - misspell
    - gocritic
    - funlen
    - gocognit
    - prealloc
    - unparam
    - unconvert
    - lll
    - whitespace
    - wsl
    - nlreturn
    - exportloopref
    - nilerr
    - predeclared
    - revive
    - goprintffuncname
    - gosec

  disable:
    - godox # Allow TODO comments
    - gomnd # Magic numbers are sometimes unavoidable
    - exhaustivestruct # Too strict for this project
    - forbidigo # We don't forbid any specific functions
    - gci # Conflicts with goimports sometimes

issues:
  exclude-rules:
    # Exclude some linters from running on tests files.
    - path: _test\.go
      linters:
        - gocyclo
        - errcheck
        - dupl
        - gosec
        - funlen
        - gocognit

    # Exclude generated files
    - path: ".*\\.pb\\.go"
      linters:
        - all

    # Exclude long lines in examples
    - path: examples/
      linters:
        - lll

  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
  new: false

severity:
  default-severity: error
