openapi: 3.1.0
info:
  title: Polymorphic API Example
  description: A comprehensive example demonstrating polymorphic types with the Gin Call method
  version: 1.0.0
paths:
  /animals:
    post:
      tags:
        - animals
      summary: Create a new animal
      description: Creates a new animal with polymorphic input supporting dogs, cats, and birds
      parameters:
        - name: source
          in: query
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              oneOf:
                - type: object
                  properties:
                    breed:
                      type: string
                    name:
                      type: string
                    isGood:
                      type: boolean
                - type: object
                  properties:
                    lives:
                      type: integer
                      format: int32
                    name:
                      type: string
                    color:
                      type: string
                - type: object
                  properties:
                    canFly:
                      type: boolean
                    name:
                      type: string
                    species:
                      type: string
                    wingspan:
                      type: integer
                      format: int32
              discriminator:
                propertyName: animalType
                mapping:
                  bird: '#/components/schemas/polymorphic.v1.Bird'
                  dog: '#/components/schemas/polymorphic.v1.Dog'
                  cat: '#/components/schemas/polymorphic.v1.Cat'
                defaultMapping: dog
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/polymorphic.v1.AnimalResponse'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                oneOf:
                  - type: object
                    properties:
                      status:
                        type: string
                      type:
                        type: string
                      message:
                        type: string
                      fields:
                        type: object
                        additionalProperties:
                          type: string
                    description: ErrorResponse represents the standard error response format.
                  - type: object
                    properties:
                      field:
                        type: string
                      code:
                        type: string
                      message:
                        type: string
                    description: Validation error response
                  - type: object
                    properties:
                      errorCode:
                        type: string
                      details:
                        type: string
                      suggestedAction:
                        type: string
                    description: Business logic error response
                  - type: object
                    properties:
                      component:
                        type: string
                      severity:
                        type: string
                      message:
                        type: string
                    description: System error response
  /animals/{id}:
    get:
      tags:
        - animals
      summary: Get an animal by ID
      description: Retrieves an animal by its unique identifier
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                    format: int64
                  createdAt:
                    type: string
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                oneOf:
                  - type: object
                    properties:
                      status:
                        type: string
                      type:
                        type: string
                      message:
                        type: string
                      fields:
                        type: object
                        additionalProperties:
                          type: string
                    description: ErrorResponse represents the standard error response format.
                  - type: object
                    properties:
                      field:
                        type: string
                      code:
                        type: string
                      message:
                        type: string
                    description: Validation error response
    put:
      tags:
        - animals
      summary: Update an animal
      description: Updates an existing animal with polymorphic input
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/polymorphic.v1.UpdateAnimalRequest'
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/polymorphic.v1.AnimalResponse'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                oneOf:
                  - type: object
                    properties:
                      status:
                        type: string
                      type:
                        type: string
                      message:
                        type: string
                      fields:
                        type: object
                        additionalProperties:
                          type: string
                    description: ErrorResponse represents the standard error response format.
                  - type: object
                    properties:
                      field:
                        type: string
                      code:
                        type: string
                      message:
                        type: string
                    description: Validation error response
  /vehicles:
    post:
      tags:
        - vehicles
      summary: Create a new vehicle
      description: Creates a new vehicle with polymorphic input using component references
      parameters:
        - name: owner
          in: query
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/polymorphic.v1.CreateVehicleRequest'
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/polymorphic.v1.VehicleResponse'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                oneOf:
                  - type: object
                    properties:
                      status:
                        type: string
                      type:
                        type: string
                      message:
                        type: string
                      fields:
                        type: object
                        additionalProperties:
                          type: string
                    description: ErrorResponse represents the standard error response format.
                  - type: object
                    properties:
                      field:
                        type: string
                      code:
                        type: string
                      message:
                        type: string
                    description: Validation error response
  /vehicles/{id}:
    get:
      tags:
        - vehicles
      summary: Get a vehicle by ID
      description: Retrieves a vehicle by its unique identifier
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                    format: int64
                  createdAt:
                    type: string
                  status:
                    type: string
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                oneOf:
                  - type: object
                    properties:
                      status:
                        type: string
                      type:
                        type: string
                      message:
                        type: string
                      fields:
                        type: object
                        additionalProperties:
                          type: string
                    description: ErrorResponse represents the standard error response format.
                  - type: object
                    properties:
                      field:
                        type: string
                      code:
                        type: string
                      message:
                        type: string
                    description: Validation error response
components:
  schemas:
    polymorphic.v1.ValidationError:
      type: object
      properties:
        field:
          type: string
        code:
          type: string
        message:
          type: string
      description: Validation error response
    polymorphic.v1.BusinessError:
      type: object
      properties:
        errorCode:
          type: string
        details:
          type: string
        suggestedAction:
          type: string
      description: Business logic error response
    polymorphic.v1.SystemError:
      type: object
      properties:
        component:
          type: string
        severity:
          type: string
        message:
          type: string
      description: System error response
    polymorphic.v1.AnimalResponse:
      type: object
      properties:
        id:
          type: integer
          format: int64
        createdAt:
          type: string
    polymorphic.v1.Bird:
      type: object
      properties:
        canFly:
          type: boolean
        name:
          type: string
        species:
          type: string
        wingspan:
          type: integer
          format: int32
    polymorphic.v1.Animal:
      oneOf:
        - type: object
          properties:
            breed:
              type: string
            name:
              type: string
            isGood:
              type: boolean
        - type: object
          properties:
            lives:
              type: integer
              format: int32
            name:
              type: string
            color:
              type: string
        - type: object
          properties:
            canFly:
              type: boolean
            name:
              type: string
            species:
              type: string
            wingspan:
              type: integer
              format: int32
      discriminator:
        propertyName: animalType
        mapping:
          bird: '#/components/schemas/polymorphic.v1.Bird'
          dog: '#/components/schemas/polymorphic.v1.Dog'
          cat: '#/components/schemas/polymorphic.v1.Cat'
        defaultMapping: dog
    polymorphic.v1.Dog:
      type: object
      properties:
        breed:
          type: string
        name:
          type: string
        isGood:
          type: boolean
    polymorphic.v1.Cat:
      type: object
      properties:
        lives:
          type: integer
          format: int32
        name:
          type: string
        color:
          type: string
    polymorphic.v1.UpdateAnimalRequest:
      oneOf:
        - type: object
          properties:
            breed:
              type: string
            name:
              type: string
            isGood:
              type: boolean
        - type: object
          properties:
            lives:
              type: integer
              format: int32
            name:
              type: string
            color:
              type: string
        - type: object
          properties:
            canFly:
              type: boolean
            name:
              type: string
            species:
              type: string
            wingspan:
              type: integer
              format: int32
      discriminator:
        propertyName: animalType
        mapping:
          dog: '#/components/schemas/polymorphic.v1.Dog'
          cat: '#/components/schemas/polymorphic.v1.Cat'
          bird: '#/components/schemas/polymorphic.v1.Bird'
        defaultMapping: dog
    polymorphic.v1.Car:
      type: object
      properties:
        doors:
          type: integer
          format: int32
        brand:
          type: string
        model:
          type: string
    polymorphic.v1.Truck:
      type: object
      properties:
        capacity:
          type: integer
          format: int32
        brand:
          type: string
        axleType:
          type: string
    polymorphic.v1.Motorcycle:
      type: object
      properties:
        ccs:
          type: integer
          format: int32
        brand:
          type: string
        type:
          type: string
    polymorphic.v1.CreateVehicleRequest:
      oneOf:
        - $ref: '#/components/schemas/polymorphic.v1.Car'
        - $ref: '#/components/schemas/polymorphic.v1.Truck'
        - $ref: '#/components/schemas/polymorphic.v1.Motorcycle'
      discriminator:
        propertyName: vehicleType
        mapping:
          car: '#/components/schemas/polymorphic.v1.Car'
          truck: '#/components/schemas/polymorphic.v1.Truck'
          motorcycle: '#/components/schemas/polymorphic.v1.Motorcycle'
        defaultMapping: car
    polymorphic.v1.VehicleResponse:
      type: object
      properties:
        id:
          type: integer
          format: int64
        createdAt:
          type: string
        status:
          type: string
    polymorphic.v1.Vehicle:
      oneOf:
        - $ref: '#/components/schemas/polymorphic.v1.Car'
        - $ref: '#/components/schemas/polymorphic.v1.Truck'
        - $ref: '#/components/schemas/polymorphic.v1.Motorcycle'
      discriminator:
        propertyName: vehicleType
        mapping:
          car: '#/components/schemas/polymorphic.v1.Car'
          truck: '#/components/schemas/polymorphic.v1.Truck'
          motorcycle: '#/components/schemas/polymorphic.v1.Motorcycle'
        defaultMapping: car
