openapi: 3.1.0
info:
  title: Swagger Petstore
servers:
  - url: http://petstore.swagger.io/v1
paths:
  /pets:
    get:
      tags:
        - pets
      summary: List all pets
      operationId: listPets
      parameters:
        - name: limit
          in: query
          required: true
          schema:
            type: integer
            format: int32
      responses:
        "200":
          description: A list of pets
          headers:
            x-next:
              description: A link to the next page of responses
              schema:
                type: string
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                      format: int64
                    name:
                      type: string
                    tag:
                      type: string
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: integer
                    format: int32
                  message:
                    type: string
    post:
      tags:
        - pets
      summary: Create a pet
      operationId: createPets
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/pet.v1.CreatePetRequest'
      responses:
        "201":
          description: Null response
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: integer
                    format: int32
                  message:
                    type: string
  /pets/{petId}:
    get:
      tags:
        - pets
      summary: Info for a specific pet
      operationId: showByPetId
      parameters:
        - name: petId
          in: path
          description: The ID of the pet to retrieve
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Expected response to a valid request
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                    format: int64
                  name:
                    type: string
                  tag:
                    type: string
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: integer
                    format: int32
                  message:
                    type: string
components:
  schemas:
    pet.v1.CreatePetRequest:
      type: object
      properties:
        pet:
          $ref: '#/components/schemas/pet.v1.Pet'
    pet.v1.Pet:
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        tag:
          type: string
