// Package compilecost measures what it costs a consumer to compile against
// arrest-go.
//
// The Go compiler re-instantiates every generic method reachable from any
// imported type a package names — through struct fields, method signatures,
// func types and inlined bodies — and compiles them all again in the
// importing package (golang/go#70511). libopenapi's model reaches thousands
// of orderedmap instantiations, so a package that so much as names
// *arrest.Document pays for all of them. This package builds probe packages
// that name each public type, counts the functions the compiler emitted into
// each, and reports build timings, so that the cost is visible and guarded.
package compilecost

import (
	"fmt"
	"go/ast"
	"go/parser"
	"go/token"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

// Probe is one generated package in the probe module.
type Probe struct {
	// Name is the package name and directory, e.g. sig_arrest_document.
	Name string
	// Kind is what the probe exercises: "sig" names a type in a function
	// signature and nothing else, "use" is a realistic consumer program,
	// "ref" is a reference point outside arrest-go's control.
	Kind string
	// Type is the type the probe names, for sig probes.
	Type string
	// Guarded reports whether the guard test holds this probe to the
	// threshold. Reference probes are informational.
	Guarded bool
	// Source is the Go source of the probe's one file.
	Source string
}

// Packages the probe module imports, and how each is spelled in a probe.
var packages = []struct {
	alias, path, dir string
}{
	{"arrest", "github.com/zostay/arrest-go", "."},
	{"arrestgin", "github.com/zostay/arrest-go/gin", "gin"},
}

// Probes enumerates the exported types of arrest and arrest/gin under root
// and returns one signature probe per type, followed by the use and reference
// probes. Types are discovered by parsing, so a new type is probed without
// anyone remembering to list it.
func Probes(root string) ([]Probe, error) {
	var probes []Probe
	for _, pkg := range packages {
		names, err := exportedTypes(filepath.Join(root, pkg.dir))
		if err != nil {
			return nil, err
		}
		for _, name := range names {
			probes = append(probes, Probe{
				Name:    fmt.Sprintf("sig_%s_%s", pkg.alias, strings.ToLower(name)),
				Kind:    "sig",
				Type:    pkg.alias + "." + name,
				Guarded: true,
				Source: fmt.Sprintf(`// Code generated by compilecost; DO NOT EDIT.

// Package %[1]s names %[2]s.%[3]s in a signature and does nothing else.
package %[1]s

import %[2]s "%[4]s"

func Probe(_ *%[2]s.%[3]s) {}
`, fmt.Sprintf("sig_%s_%s", pkg.alias, strings.ToLower(name)), pkg.alias, name, pkg.path),
			})
		}
	}

	probes = append(probes,
		Probe{Name: "use_arrest", Kind: "use", Guarded: true, Source: useArrest},
		Probe{Name: "use_gin", Kind: "use", Guarded: true, Source: useGin},
		Probe{Name: "ref_blank", Kind: "ref", Source: refBlank},
		Probe{Name: "ref_v3", Kind: "ref", Source: refV3},
	)
	return probes, nil
}

// exportedTypes lists the exported named types declared in the non-test Go
// files of dir, sorted.
func exportedTypes(dir string) ([]string, error) {
	entries, err := os.ReadDir(dir)
	if err != nil {
		return nil, err
	}

	fset := token.NewFileSet()
	var names []string
	for _, entry := range entries {
		name := entry.Name()
		if entry.IsDir() || !strings.HasSuffix(name, ".go") || strings.HasSuffix(name, "_test.go") {
			continue
		}
		file, err := parser.ParseFile(fset, filepath.Join(dir, name), nil, parser.SkipObjectResolution)
		if err != nil {
			return nil, fmt.Errorf("parse %s: %w", name, err)
		}
		for _, decl := range file.Decls {
			gd, ok := decl.(*ast.GenDecl)
			if !ok || gd.Tok != token.TYPE {
				continue
			}
			for _, spec := range gd.Specs {
				ts := spec.(*ast.TypeSpec)
				if ts.Name.IsExported() {
					names = append(names, ts.Name.Name)
				}
			}
		}
	}
	sort.Strings(names)
	return names, nil
}

// The use probes are what a small real consumer looks like. They exist to
// catch what the signature probes cannot: a libopenapi type reached through
// the body of an inlined method or an instantiated generic function.

const useArrest = `// Package use_arrest is a small consumer of the arrest DSL.
package use_arrest

import (
	"reflect"

	arrest "github.com/zostay/arrest-go"
)

// Pet is a pet.
type Pet struct {
	ID   int64  ` + "`json:\"id\"`" + `
	Name string ` + "`json:\"name\"`" + `
	Tag  string ` + "`json:\"tag,omitempty\"`" + `
}

// Error is an error.
type Error struct {
	Code    int32  ` + "`json:\"code\"`" + `
	Message string ` + "`json:\"message\"`" + `
}

func listPets(limit int32) ([]Pet, error) { return nil, nil }

// Build builds the document and renders it.
func Build() ([]byte, error) {
	doc, err := arrest.NewDocument("probe")
	if err != nil {
		return nil, err
	}

	doc.Version("1.0.0").
		Description("A probe.").
		AddServer("http://localhost/v1").
		PackageMap("probe", "probe/use_arrest")

	errModel := arrest.ModelFrom[Error](doc, arrest.AsComponent()).Description("An error.")

	doc.Get("/pets").
		OperationID("listPets").
		Tags("pets").
		Summary("List pets").
		Parameters(arrest.ParametersFromReflect(reflect.TypeOf(listPets)).
			P(0, func(p *arrest.Parameter) { p.Name("limit").InQuery() })).
		Response("200", func(r *arrest.Response) {
			r.Description("Pets").
				Header("x-next", arrest.ModelFrom[string](doc), func(h *arrest.Header) {
					h.Description("Next page")
				}).
				Content("application/json", arrest.ModelFrom[[]Pet](doc))
		}).
		Response("default", func(r *arrest.Response) {
			r.Description("Unexpected error").Content("application/json", errModel)
		})

	doc.Post("/pets").
		OperationID("createPet").
		Tags("pets").
		RequestBody("application/json", arrest.ModelFrom[Pet](doc, arrest.WithComponentName("NewPet"))).
		Response("201", func(r *arrest.Response) { r.Description("Created") })

	if err := doc.Err(); err != nil {
		return nil, err
	}
	if err := doc.Refresh(); err != nil {
		return nil, err
	}
	return doc.Render()
}
`

const useGin = `// Package use_gin is a small consumer of the arrest gin integration.
package use_gin

import (
	"context"

	"github.com/gin-gonic/gin"
	arrest "github.com/zostay/arrest-go"
	arrestgin "github.com/zostay/arrest-go/gin"
)

// PetRequest asks for one pet.
type PetRequest struct {
	ID int64 ` + "`json:\"id\" openapi:\",in=path\"`" + `
}

// Pet is a pet.
type Pet struct {
	ID   int64  ` + "`json:\"id\"`" + `
	Name string ` + "`json:\"name\"`" + `
}

func getPet(ctx context.Context, req PetRequest) (*Pet, error) { return &Pet{ID: req.ID}, nil }

func handleError(_ *gin.Context, err error) interface{} {
	return &arrestgin.ErrorResponse{Status: "error", Message: err.Error()}
}

// Build builds the router and document and renders the document.
func Build() (*gin.Engine, []byte, error) {
	doc, err := arrest.NewDocument("probe")
	if err != nil {
		return nil, nil, err
	}
	doc.Version("1.0.0").PackageMap("probe", "probe/use_gin")

	router := gin.New()
	d := arrestgin.NewDocument(doc, router)
	d.Get("/pets/{id}").
		OperationID("getPet").
		Tags("pets").
		Summary("Get a pet").
		Call(getPet, arrestgin.WithErrorHandler(handleError), arrestgin.WithComponents())

	if err := doc.Err(); err != nil {
		return nil, nil, err
	}
	bs, err := doc.Render()
	return router, bs, err
}
`

const refBlank = `// Package ref_blank imports arrest and names nothing. It should cost nothing.
package ref_blank

import _ "github.com/zostay/arrest-go"
`

const refV3 = `// Package ref_v3 names libopenapi's own v3.Document: the floor libopenapi
// imposes on any package that reaches its model, which arrest-go cannot lower.
package ref_v3

import v3 "github.com/pb33f/libopenapi/datamodel/high/v3"

func Probe(_ *v3.Document) {}
`
